
collect: 
  module: "DataLoader"
  config: 
    data_dir: "data/train/"
  
preprocess:
  add_features:
    - module: TextLanguageFeature
      config:
        input_column_name: "text_column"
        output_column_name: "language"

train:
  model:
    module: "TrainPipeline"
    config:
      # the portion to be used for trainining (and validation). The rest for testing
      train_split: 0.7
      features:
        - "review_body_length"
        - "review_header_length"
      target: "label"
      save_dir: "model"
      overwrite: True


  save:

evaluate:

predict:



