
collect: 
  module: "DataLoader"
  config: 
    data_dir: "data/train/"
  
preprocess:
  add_features:
    - module: TextLengthFeature
      config:
        input_column_name: "review_body"
        output_column_name: "review_body_length"
    - module: TextLengthFeature
      config:
        input_column_name: "review_headline"
        output_column_name: "review_headline_length"

train:
  model:
    module: "TrainPipeline"
    config:
      # the portion to be used for trainining (and validation). The rest for testing
      train_split: 0.7
      features:
        - "review_body_length"
        - "review_headline_length"
      target: "label"
      save_dir: "model"
      overwrite: True

predict:
  data_dir:
    - "data/predict/"
  predictions_dir:
    - "predictions/"
  overwrite: True




