collect: 
  module: "DataLoader"
  config: 
    data_dir: "data/predict/"
    # we want to keep two dataframes for predictions
    merge: False #FIXME: if this is set to true, saving predictions will fail

raw_data_quality_check:
  module: "GXDataQualityCheckModule"
  config:
    expectation_suite_name: "predictions_raw_data_expectation_suite"
    continue_after_failure: False

preprocess:
  clean:
    - module: ConvertToBoolean
      config:
        input_column_name: "verified_purchase"
        output_column_name: "verified_purchase"
        mapping: {"Y": True, "N": False}
        map_non_matches_to: False

    - module: ConvertToBoolean
      config:
        input_column_name: "vine"
        output_column_name: "vine"
        mapping: {"Y": True, "N": False}
        map_non_matches_to: False

  add_features:
    - module: "CharacterCountModule"
      config:
        input_column_name: "review_body"
        output_column_name: "num_exlamation_marks"
        characters_to_count: ["!"]

    - module: "CharacterCountModule"
      config:
        input_column_name: "review_body"
        output_column_name: "num_question_marks"
        characters_to_count: ["?"]

    - module: "CharacterCountModule"
      config:
        input_column_name: "review_body"
        output_column_name: "num_periods"
        characters_to_count: ["."]
    
    - module: TextLengthFeature
      config:
        input_column_name: "review_body"
        output_column_name: "review_body_length"
    - module: TextLengthFeature
      config:
        input_column_name: "review_headline"
        output_column_name: "review_headline_length"
   
  
  impute_missing_values:
    - module: ImputationModule
      config:
        column_name: "product_category_id"
        imputation_method: "constant"
        imputation_value: 1
    - module: ImputationModule
      config:
        column_name: "marketplace_id"
        imputation_method: "constant"
        imputation_value: 1

  transform:
    - module: "OneHotEncodingModule"
      config:
        input_column_name: "marketplace_id"
        output_column_name: "marketplace_id_encoded"

    # - module: "OneHotEncodingModule"
    #   config:
    #     input_column_name: "product_category_id"
    #     output_column_name: "product_category_id_encoded"
    - module: HashingModule
      config:
        input_column_name: "product_category_id"
        output_column_name: "product_category_id_encoded"
        num_features: 29

load_model:
  model_path: "model"

predict:
  save_dir: "predictions/"
  overwrite: True




